//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.AuthTexts", typeof(AuthTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account_Default {
            get {
                return ResourceManager.GetString("Account_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Btn_Login {
            get {
                return ResourceManager.GetString("Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Btn_Register {
            get {
                return ResourceManager.GetString("Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại.
        /// </summary>
        public static string Btn_Resend {
            get {
                return ResourceManager.GetString("Btn_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string Btn_ResetPassword {
            get {
                return ResourceManager.GetString("Btn_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi OTP.
        /// </summary>
        public static string Btn_SendOtp {
            get {
                return ResourceManager.GetString("Btn_SendOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Btn_Verify {
            get {
                return ResourceManager.GetString("Btn_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhàNow - Đặt lại mật khẩu.
        /// </summary>
        public static string Email_Subject_Reset {
            get {
                return ResourceManager.GetString("Email_Subject_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhàNow - Mã xác thực email.
        /// </summary>
        public static string Email_Subject_Verify {
            get {
                return ResourceManager.GetString("Email_Subject_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ. Vui lòng kiểm tra lại..
        /// </summary>
        public static string Err_InvalidData {
            get {
                return ResourceManager.GetString("Err_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tài khoản hoặc mật khẩu..
        /// </summary>
        public static string Err_LoginInvalid {
            get {
                return ResourceManager.GetString("Err_LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không hợp lệ..
        /// </summary>
        public static string Err_OtpInvalid {
            get {
                return ResourceManager.GetString("Err_OtpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi email thất bại. Vui lòng thử lại..
        /// </summary>
        public static string Err_SendEmailFailed {
            get {
                return ResourceManager.GetString("Err_SendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string Forgot_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Forgot_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đăng ký.
        /// </summary>
        public static string Forgot_Email {
            get {
                return ResourceManager.GetString("Forgot_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string Forgot_NewPassword {
            get {
                return ResourceManager.GetString("Forgot_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string Forgot_ResetButton {
            get {
                return ResourceManager.GetString("Forgot_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi mã.
        /// </summary>
        public static string Forgot_SendOtp {
            get {
                return ResourceManager.GetString("Forgot_SendOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu.
        /// </summary>
        public static string Forgot_Title {
            get {
                return ResourceManager.GetString("Forgot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã được gửi. Vui lòng kiểm tra email..
        /// </summary>
        public static string Hint_VerifySent {
            get {
                return ResourceManager.GetString("Hint_VerifySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc SĐT.
        /// </summary>
        public static string Label_LoginName {
            get {
                return ResourceManager.GetString("Label_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP.
        /// </summary>
        public static string Label_Otp {
            get {
                return ResourceManager.GetString("Label_Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string Link_Forgot {
            get {
                return ResourceManager.GetString("Link_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc SĐT.
        /// </summary>
        public static string Login_EmailOrPhone {
            get {
                return ResourceManager.GetString("Login_EmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string Login_Forgot {
            get {
                return ResourceManager.GetString("Login_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại..
        /// </summary>
        public static string Msg_EmailExists {
            get {
                return ResourceManager.GetString("Msg_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email..
        /// </summary>
        public static string Msg_EmailRequired {
            get {
                return ResourceManager.GetString("Msg_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai email/SĐT hoặc mật khẩu..
        /// </summary>
        public static string Msg_InvalidCredentials {
            get {
                return ResourceManager.GetString("Msg_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa xác thực email. Vui lòng nhập OTP..
        /// </summary>
        public static string Msg_NeedVerify {
            get {
                return ResourceManager.GetString("Msg_NeedVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn. Vui lòng gửi lại mã..
        /// </summary>
        public static string Msg_OtpExpired {
            get {
                return ResourceManager.GetString("Msg_OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP sẽ hết hạn sau 5 phút..
        /// </summary>
        public static string Msg_OtpExpiresIn5Min {
            get {
                return ResourceManager.GetString("Msg_OtpExpiresIn5Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không hợp lệ..
        /// </summary>
        public static string Msg_OtpInvalid {
            get {
                return ResourceManager.GetString("Msg_OtpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi lại OTP..
        /// </summary>
        public static string Msg_OtpResent {
            get {
                return ResourceManager.GetString("Msg_OtpResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi OTP thất bại. Vui lòng thử lại..
        /// </summary>
        public static string Msg_OtpSendFail {
            get {
                return ResourceManager.GetString("Msg_OtpSendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi OTP về email..
        /// </summary>
        public static string Msg_OtpSent {
            get {
                return ResourceManager.GetString("Msg_OtpSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập lại không khớp..
        /// </summary>
        public static string Msg_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại..
        /// </summary>
        public static string Msg_PhoneExists {
            get {
                return ResourceManager.GetString("Msg_PhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu thành công..
        /// </summary>
        public static string Msg_ResetSuccess {
            get {
                return ResourceManager.GetString("Msg_ResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực thành công..
        /// </summary>
        public static string Msg_VerifySuccess {
            get {
                return ResourceManager.GetString("Msg_VerifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP.
        /// </summary>
        public static string Otp_Code {
            get {
                return ResourceManager.GetString("Otp_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại mã.
        /// </summary>
        public static string Otp_Resend {
            get {
                return ResourceManager.GetString("Otp_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực email.
        /// </summary>
        public static string Otp_Title {
            get {
                return ResourceManager.GetString("Otp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực.
        /// </summary>
        public static string Otp_VerifyButton {
            get {
                return ResourceManager.GetString("Otp_VerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string Register_DisplayName {
            get {
                return ResourceManager.GetString("Register_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Register_Phone {
            get {
                return ResourceManager.GetString("Register_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Xác thực email.
        /// </summary>
        public static string Verify_Title {
            get {
                return ResourceManager.GetString("Verify_Title", resourceCulture);
            }
        }
    }
}
