//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeNow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeNow.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam kết và bảo đảm dịch vụ trung thực của công ty môi giới bất động sản.
        /// </summary>
        public static string BottomNote {
            get {
                return ResourceManager.GetString("BottomNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đà Nẵng.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử Nghiệm logo.
        /// </summary>
        public static string LogoTagline {
            get {
                return ResourceManager.GetString("LogoTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà thật – Thông tin thật – Trải nghiệm thật.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string MapLabel {
            get {
                return ResourceManager.GetString("MapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán Nhà.
        /// </summary>
        public static string NavBuy {
            get {
                return ResourceManager.GetString("NavBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin.
        /// </summary>
        public static string NavPostListing {
            get {
                return ResourceManager.GetString("NavPostListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuê Nhà.
        /// </summary>
        public static string NavRent {
            get {
                return ResourceManager.GetString("NavRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu tìm nhà.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập quận, khu vực hoặc tên đường để bắt đầu tìm nhà….
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ở đâu cũng xem được! Khám phá phòng bằng VR 360°.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử nghiệm.
        /// </summary>
        public static string TabFindApartment {
            get {
                return ResourceManager.GetString("TabFindApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thử nghiệm TabFindArea.
        /// </summary>
        public static string TabFindArea {
            get {
                return ResourceManager.GetString("TabFindArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm phòng trọ.
        /// </summary>
        public static string TabFindRoom {
            get {
                return ResourceManager.GetString("TabFindRoom", resourceCulture);
            }
        }
    }
}
