//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeNow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeNow.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account_Default {
            get {
                return ResourceManager.GetString("Account_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam kết và bảo đảm dịch vụ trung thực của công ty môi giới bất động sản.
        /// </summary>
        public static string BottomNote {
            get {
                return ResourceManager.GetString("BottomNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà Nội
        ///.
        /// </summary>
        public static string Brand_City {
            get {
                return ResourceManager.GetString("Brand_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhàNow
        ///.
        /// </summary>
        public static string Brand_Name {
            get {
                return ResourceManager.GetString("Brand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đà Nẵng.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực Đăng ký &amp; Liên hệ
        ///.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        public static string Currency_VND {
            get {
                return ResourceManager.GetString("Currency_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần đăng nhập để sử dụng chức năng Yêu thích..
        /// </summary>
        public static string Favorite_NeedLogin {
            get {
                return ResourceManager.GetString("Favorite_NeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật Yêu thích. Vui lòng thử lại..
        /// </summary>
        public static string Favorite_UpdateFailed {
            get {
                return ResourceManager.GetString("Favorite_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh 360° Chuyên nghiệp
        ///.
        /// </summary>
        public static string Feature_360 {
            get {
                return ResourceManager.GetString("Feature_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp cận tối đa Khách thuê
        ///.
        /// </summary>
        public static string Feature_Reach {
            get {
                return ResourceManager.GetString("Feature_Reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiết kiệm thời gian Quản lý
        ///.
        /// </summary>
        public static string Feature_TimeSaving {
            get {
                return ResourceManager.GetString("Feature_TimeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các căn cho thuê nổi bật.
        /// </summary>
        public static string FeaturedRent_Title {
            get {
                return ResourceManager.GetString("FeaturedRent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các căn bán nổi bật.
        /// </summary>
        public static string FeaturedSale_Title {
            get {
                return ResourceManager.GetString("FeaturedSale_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại sao chọn NhàNow?
        ///.
        /// </summary>
        public static string Features_Title {
            get {
                return ResourceManager.GetString("Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố.
        /// </summary>
        public static string Filter_City {
            get {
                return ResourceManager.GetString("Filter_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mốc giá.
        /// </summary>
        public static string Filter_Price {
            get {
                return ResourceManager.GetString("Filter_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Loại nhà.
        /// </summary>
        public static string Filter_PropertyType {
            get {
                return ResourceManager.GetString("Filter_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ BĐS
        ///.
        /// </summary>
        public static string Form_AddressPlaceholder {
            get {
                return ResourceManager.GetString("Form_AddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên
        ///.
        /// </summary>
        public static string Form_FullNamePlaceholder {
            get {
                return ResourceManager.GetString("Form_FullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để lại thông tin đăng ký
        ///.
        /// </summary>
        public static string Form_Header {
            get {
                return ResourceManager.GetString("Form_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói Quản lý
        ///.
        /// </summary>
        public static string Form_OptionManage {
            get {
                return ResourceManager.GetString("Form_OptionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói Media
        ///.
        /// </summary>
        public static string Form_OptionMedia {
            get {
                return ResourceManager.GetString("Form_OptionMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại
        ///.
        /// </summary>
        public static string Form_PhonePlaceholder {
            get {
                return ResourceManager.GetString("Form_PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu ngay
        ///.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ TƯ VẤN MIỄN PHÍ
        ///.
        /// </summary>
        public static string Hero_CTA {
            get {
                return ResourceManager.GetString("Hero_CTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi lo hình ảnh, marketing và dẫn khách. Bạn chỉ việc nhận tiền.
        ///.
        /// </summary>
        public static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nâng tầm Bất động sản của bạn với Công nghệ VR
        ///.
        /// </summary>
        public static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử Nghiệm logo.
        /// </summary>
        public static string LogoTagline {
            get {
                return ResourceManager.GetString("LogoTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà thật – Thông tin thật – Trải nghiệm thật.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string MapLabel {
            get {
                return ResourceManager.GetString("MapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua nhà
        ///.
        /// </summary>
        public static string Menu_Buy {
            get {
                return ResourceManager.GetString("Menu_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin
        ///.
        /// </summary>
        public static string Menu_Post {
            get {
                return ResourceManager.GetString("Menu_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuê nhà
        ///.
        /// </summary>
        public static string Menu_Rent {
            get {
                return ResourceManager.GetString("Menu_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhàNow - Nâng tầm Bất động sản.
        /// </summary>
        public static string Meta_HtmlTitle {
            get {
                return ResourceManager.GetString("Meta_HtmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin chủ nhà - NhàNow (Preview.
        /// </summary>
        public static string Meta_PageTitle {
            get {
                return ResourceManager.GetString("Meta_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán Nhà.
        /// </summary>
        public static string NavBuy {
            get {
                return ResourceManager.GetString("NavBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin.
        /// </summary>
        public static string NavPostListing {
            get {
                return ResourceManager.GetString("NavPostListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuê Nhà.
        /// </summary>
        public static string NavRent {
            get {
                return ResourceManager.GetString("NavRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhàNow - Tìm nhà dễ dàng.
        /// </summary>
        public static string PageTitle_Home {
            get {
                return ResourceManager.GetString("PageTitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Gửi yêu cầu
        ///.
        /// </summary>
        public static string Process_Step1 {
            get {
                return ResourceManager.GetString("Process_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Đội ngũ Media đến
        ///.
        /// </summary>
        public static string Process_Step2 {
            get {
                return ResourceManager.GetString("Process_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. NhàNow dẫn khách
        ///.
        /// </summary>
        public static string Process_Step3 {
            get {
                return ResourceManager.GetString("Process_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Chốt &amp; Nhận tiền
        ///.
        /// </summary>
        public static string Process_Step4 {
            get {
                return ResourceManager.GetString("Process_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình hợp tác đơn giản
        ///.
        /// </summary>
        public static string Process_Title {
            get {
                return ResourceManager.GetString("Process_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy căn phù hợp, bạn thử thay đổi điều kiện tìm kiếm nhé..
        /// </summary>
        public static string Search_NotFound {
            get {
                return ResourceManager.GetString("Search_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ hoặc  tên bất động sản....
        /// </summary>
        public static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu tìm nhà.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string SearchResult_Title {
            get {
                return ResourceManager.GetString("SearchResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ở đâu cũng xem được! Khám phá phòng bằng VR 360°.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuê nhà.
        /// </summary>
        public static string Tab_Rent {
            get {
                return ResourceManager.GetString("Tab_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mua nhà.
        /// </summary>
        public static string Tab_Sale {
            get {
                return ResourceManager.GetString("Tab_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử nghiệm.
        /// </summary>
        public static string TabFindApartment {
            get {
                return ResourceManager.GetString("TabFindApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thử nghiệm TabFindArea.
        /// </summary>
        public static string TabFindArea {
            get {
                return ResourceManager.GetString("TabFindArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm phòng trọ.
        /// </summary>
        public static string TabFindRoom {
            get {
                return ResourceManager.GetString("TabFindRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC.
        /// </summary>
        public static string Unit_Bathroom {
            get {
                return ResourceManager.GetString("Unit_Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PN.
        /// </summary>
        public static string Unit_Bedroom {
            get {
                return ResourceManager.GetString("Unit_Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
    }
}
